// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo19GVxhz7od9yAWkoiESIk4tqrXye2Zw',
    appId: '1:547834534070:android:172726c6adec3bd2b32e17',
    messagingSenderId: '547834534070',
    projectId: 'videoreviews-7ecf0',
    storageBucket: 'videoreviews-7ecf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9jBY1aLxcmVm2VVpyXNCd5cVT55zNexM',
    appId: '1:547834534070:ios:edd235cc82990c40b32e17',
    messagingSenderId: '547834534070',
    projectId: 'videoreviews-7ecf0',
    storageBucket: 'videoreviews-7ecf0.appspot.com',
    androidClientId: '547834534070-n8mmq3qu96u4lagj9r3lbf20bhtm71n4.apps.googleusercontent.com',
    iosClientId: '547834534070-0290gtho2l03bgd2gd7pt10ok76cucog.apps.googleusercontent.com',
    iosBundleId: 'com.example.videodemo',
  );
}
